/**
 * Agent 类型定义
 * 从 core/types.ts 重新导出，保持兼容性
 */

export type {
  ToolStatus,
  ToolApprovalType,
  ToolCall,
  ToolDefinition,
  TextContent,
  ImageContent,
  MessageContent,
  FileSnapshot,
  UserMessage,
  TextPart,
  ToolCallPart,
  AssistantPart,
  AssistantMessage,
  ToolResultType,
  ToolResultMessage,
  CheckpointMessage,
  InterruptedToolMessage,
  ChatMessage,
  ContextItemType,
  FileContext,
  CodeSelectionContext,
  FolderContext,
  CodebaseContext,
  GitContext,
  TerminalContext,
  SymbolsContext,
  ContextItem,
  ThreadState,
  ChatThread,
  StreamPhase,
  StreamState,
  PendingChange,
  MessageCheckpoint,
  AgentConfig,
} from '../../agent/core/types'

export {
  isUserMessage,
  isAssistantMessage,
  isToolResultMessage,
  isCheckpointMessage,
  isInterruptedToolMessage,
  isTextPart,
  isToolCallPart,
  getMessageText,
  getMessageImages,
  getModifiedFilesFromMessages,
  findLastCheckpointIndex,
} from '../../agent/core/types'
